language: ruby
rvm:
  - 2.7

env:
  - JEKYLL_ENV=production

install:
  - bundle install
script:
  - bundle exec jekyll build -d _site

cache:
  bundler: true

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
