language: ruby
rvm:
  - 2.5.1

install: bundle install
script: bundle exec jekyll build -d _site

branches:
  only:
  - master

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change
