language: ruby
rvm:
  - 2.5
sudo: false

env:
  - JEKYLL_ENV=production
install:
  - bundle install
script:
  - bundle exec jekyll build -d _site

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
