name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Build GitHub Pages
        env:
          JEKYLL_ENV: production
          LC_ALL: C.UTF-8
        run: |
          bundle exec jekyll build
      - name: Upload GitHub Pages to artifact
        uses: actions/upload-artifact@v2
        with:
          name: gh-pages
          path: _site

  deploy:
    name: Deploy
    needs:
      - build
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Download GitHub Pages from artifact
        uses: actions/download-artifact@v2
        with:
          name: gh-pages
          path: ${{ runner.temp }}
      - name: Sync changes to GitHub Pages branch
        run: |
          rsync --archive --checksum --delete-after --exclude=.git "${RUNNER_TEMP}/" .
          touch .nojekyll
      - name: Push changes to GitHub Pages branch
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '4189282+github-actions[bot]@users.noreply.github.com'
          git add --all .
          git commit --message="Deploy GitHub Pages from commit $(git rev-parse --short "${GITHUB_SHA}")" || true
          git push origin gh-pages
