name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pages:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production
      LC_ALL: C.UTF-8
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Setup Jekyll
        run: |
          gem install bundler
          bundle install
      - name: Build Jekyll
        run: |
          bundle exec jekyll build -d _site
